#!/bin/sh -x
set -e
cwd=`pwd`
tmpdir=$cwd/bootstrap_install.$$
mkdir $tmpdir

# Install ruby
cd $tmpdir
RUBY=ruby-1.8.7-p302
RUBYGEMS=rubygems-1.3.7
wget http://ftp.ruby-lang.org/pub/ruby/1.8/$RUBY.tar.bz2
tar hxf $RUBY.tar.bz2
cd $RUBY
./configure --prefix=/opt/ruby
make
make install

# Install rubygems and important gems
cd $tmpdir
wget http://production.cf.rubygems.org/rubygems/$RUBYGEMS.tgz
tar zxf $RUBYGEMS.tgz
cd $RUBYGEMS
/opt/ruby/bin/ruby setup.rb
/opt/ruby/bin/gem install bundler 
/opt/ruby/bin/gem install chef --no-ri --no-rdoc --version 0.9.2

# Build ruby-shadow for chef shadow password support
cd $tmpdir
wget http://pkgs.repoforge.org/ruby-shadow/ruby-shadow-1.4.1-1.rf.src.rpm
rpm -i --nomd5 ruby-shadow-1.4.1-1.rf.src.rpm
tar zxf /usr/src/redhat/SOURCES/ruby-shadow-1.4.1.tar.gz
cd shadow-1.4.1
/opt/ruby/bin/ruby extconf.rb
make
make install

#cleanup
cd $cwd
rm -rf $tmpdir
